# Generated by Django 5.0 on 2025-11-16 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('custody_type', models.CharField(choices=[('laptop', 'جهاز كمبيوتر محمول'), ('desktop', 'جهاز كمبيوتر مكتبي'), ('mobile', 'هاتف محمول'), ('vehicle', 'مركبة'), ('tools', 'أدوات'), ('keys', 'مفاتيح'), ('card', 'بطاقة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع العهدة')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='وصف الصنف')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم التسلسلي')),
                ('item_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة الصنف')),
                ('issue_date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('returned', 'مُرتجعة'), ('lost', 'مفقودة'), ('damaged', 'تالفة')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodies', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'عهدة موظف',
                'verbose_name_plural': 'عهد الموظفين',
                'db_table': 'Tbl_Employee_Custody',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('insurance_type', models.CharField(choices=[('social', 'تأمينات اجتماعية'), ('health', 'تأمين صحي')], max_length=20, verbose_name='نوع التأمين')),
                ('insurance_number', models.CharField(max_length=50, verbose_name='رقم التأمين')),
                ('insurance_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='شركة التأمين')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة التغطية')),
                ('monthly_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القسط الشهري')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'تأمين موظف',
                'verbose_name_plural': 'تأمينات الموظفين',
                'db_table': 'Tbl_Employee_Insurance',
                'ordering': ['-start_date'],
            },
        ),
    ]
