# Generated by Django 5.0 on 2025-11-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeecustody_employeeinsurance'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_certificate',
            field=models.BooleanField(default=False, verbose_name='شهادة الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='car_pickup_point',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نقطة التقاط السيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='car_ride_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت ركوب السيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirm_exit_insurance',
            field=models.BooleanField(default=False, verbose_name='تأكيد خروج التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تجديد العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='شهر تجديد العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='criminal_record_check',
            field=models.BooleanField(default=False, verbose_name='فيش وتشبيه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_week_shift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وردية الأسبوع الحالي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_contract_submitted',
            field=models.BooleanField(default=False, verbose_name='عقد العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1',
            field=models.BooleanField(default=False, verbose_name='نموذج 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تسليم نموذج 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ دخول نموذج 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1_entry_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم دخول نموذج 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s1_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استلام نموذج 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6',
            field=models.BooleanField(default=False, verbose_name='نموذج 6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تسليم نموذج 6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ دخول نموذج 6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6_entry_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم دخول نموذج 6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='form_s6_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استلام نموذج 6'),
        ),
        migrations.AddField(
            model_name='employee',
            name='friday_operation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عمل يوم الجمعة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم الكامل بالعربية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الكامل بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_car',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لديه سيارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_remaining_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='الأيام المتبقية لانتهاء البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تجديد البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_card_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية البطاقة الصحية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card_photo',
            field=models.BooleanField(default=False, verbose_name='صورة البطاقة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='مبلغ التأمين المستحق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='كود التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_entry_confirmation',
            field=models.BooleanField(default=False, verbose_name='تأكيد دخول التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_job_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='كود الوظيفة للتأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_job_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الوظيفة للتأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='نسبة التأمين المستحقة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_printout',
            field=models.BooleanField(default=False, verbose_name='مطبوعة التأمينات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='راتب التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة التأمين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_exam_form_submission',
            field=models.BooleanField(default=False, verbose_name='تقديم نموذج الفحص الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_exam_form_submitted',
            field=models.BooleanField(default=False, verbose_name='نموذج الفحص الطبي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_service_certificate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهادة الخدمة العسكرية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الأم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_week_shift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وردية الأسبوع القادم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_incoming_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ وارد الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_incoming_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم وارد الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_insurance_entry_confirmation',
            field=models.BooleanField(default=False, verbose_name='تأكيد دخول تأمين الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_s1',
            field=models.BooleanField(default=False, verbose_name='نموذج 1 الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_s1_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تسليم نموذج 1 الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_s1_receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استلام نموذج 1 الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_s6',
            field=models.BooleanField(default=False, verbose_name='نموذج 6 الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_subscription_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء اشتراك الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orient_subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية اشتراك الدولية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='people_with_special_needs',
            field=models.BooleanField(default=False, verbose_name='من ذوي الاحتياجات الخاصة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_photos',
            field=models.BooleanField(default=False, verbose_name='صور شخصية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف 2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مكان الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification_certificate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهادة المؤهل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='remaining_contract_renewal',
            field=models.IntegerField(blank=True, null=True, verbose_name='المتبقي لتجديد العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستقالة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سبب الاستقالة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الثاني بالعربية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_paper',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ورقة الوردية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الوردية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skill_level_measurement_certificate',
            field=models.BooleanField(default=False, verbose_name='شهادة قياس مستوى المهارة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_status_report',
            field=models.BooleanField(default=False, verbose_name='بحث حالة اجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='معرف تيليجرام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='إجمالي الراتب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_salary_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='إجمالي الراتب نصاً'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_heel',
            field=models.BooleanField(default=False, verbose_name='كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_heel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_heel_recipient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مستلم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_heel_recipient_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان مستلم كعب العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حالة العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='years_since_contract_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السنوات منذ بداية العقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('temporary', 'مؤقت'), ('intern', 'متدرب')], default='full_time', max_length=50, null=True, verbose_name='نوع الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name_ar',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول بالعربية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الأول بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم العائلة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], default='single', max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='رقم الهوية الوطنية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='سعودي', max_length=50, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.position', verbose_name='المنصب'),
        ),
    ]
