# Generated by Django 5.2.8 on 2025-12-03 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_birth_certificate_employee_car_pickup_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('education_level', models.CharField(choices=[('primary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('doctorate', 'دكتوراه'), ('other', 'أخرى')], max_length=20, verbose_name='المستوى التعليمي')),
                ('major', models.CharField(max_length=200, verbose_name='التخصص')),
                ('institution_name', models.CharField(max_length=200, verbose_name='اسم المؤسسة التعليمية')),
                ('graduation_year', models.IntegerField(verbose_name='سنة التخرج')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='الدرجة/التقدير')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employees/certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='ملف الشهادة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'مؤهل موظف',
                'verbose_name_plural': 'مؤهلات الموظفين',
                'db_table': 'Tbl_Employee_Qualifications',
                'ordering': ['-graduation_year'],
            },
        ),
    ]
