# Generated by Django 5.0 on 2025-11-16 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(default='نظام إدارة الموارد البشرية', max_length=200, verbose_name='اسم الشركة (عربي)')),
                ('company_name_en', models.CharField(default='HR Management System', max_length=200, verbose_name='اسم الشركة (إنجليزي)')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='عنوان الشركة')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الشركة')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار الشركة')),
                ('font_family', models.CharField(choices=[('Cairo', 'Cairo'), ('Tajawal', 'Tajawal'), ('Almarai', 'Almarai'), ('Amiri', 'Amiri'), ('Noto Sans Arabic', 'Noto Sans Arabic')], default='Cairo', max_length=50, verbose_name='نوع الخط')),
                ('font_size', models.CharField(choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير')], default='medium', max_length=10, verbose_name='حجم الخط')),
                ('theme_color', models.CharField(default='#667eea', max_length=7, verbose_name='اللون الأساسي')),
                ('rtl_enabled', models.BooleanField(default=True, verbose_name='تفعيل الاتجاه من اليمين لليسار')),
                ('date_format', models.CharField(choices=[('d/m/Y', 'يوم/شهر/سنة'), ('Y-m-d', 'سنة-شهر-يوم'), ('d-m-Y', 'يوم-شهر-سنة')], default='d/m/Y', max_length=10, verbose_name='تنسيق التاريخ')),
                ('time_format', models.CharField(choices=[('12', '12 ساعة'), ('24', '24 ساعة')], default='12', max_length=2, verbose_name='تنسيق الوقت')),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='اللغة الافتراضية')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('currency', models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('AED', 'درهم إماراتي')], default='SAR', max_length=3, verbose_name='العملة')),
                ('pagination_size', models.IntegerField(default=20, verbose_name='عدد السجلات في الصفحة')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='مدة انتهاء الجلسة (دقيقة)')),
                ('smtp_server', models.CharField(blank=True, max_length=100, null=True, verbose_name='خادم SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='منفذ SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم مستخدم SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة مرور SMTP')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات البريد الإلكتروني')),
                ('password_min_length', models.IntegerField(default=8, verbose_name='الحد الأدنى لطول كلمة المرور')),
                ('password_require_uppercase', models.BooleanField(default=True, verbose_name='يتطلب أحرف كبيرة')),
                ('password_require_lowercase', models.BooleanField(default=True, verbose_name='يتطلب أحرف صغيرة')),
                ('password_require_numbers', models.BooleanField(default=True, verbose_name='يتطلب أرقام')),
                ('password_require_special', models.BooleanField(default=False, verbose_name='يتطلب رموز خاصة')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية')),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='الحد الأقصى لمحاولات تسجيل الدخول')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحديث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
                'db_table': 'Tbl_Company_Settings',
            },
        ),
    ]
