# Generated by Django 5.2.8 on 2025-11-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='اسم المتقدم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('resume', models.FileField(upload_to='recruitment/resumes/', verbose_name='السيرة الذاتية')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='خطاب التقديم')),
                ('status', models.CharField(choices=[('received', 'مستلم'), ('screening', 'فحص أولي'), ('interview', 'مقابلة'), ('offer', 'عرض'), ('hired', 'تم التوظيف'), ('rejected', 'مرفوض')], default='received', max_length=20, verbose_name='الحالة')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'db_table': 'Tbl_Job_Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('interview_date', models.DateTimeField(verbose_name='تاريخ ووقت المقابلة')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('result', models.CharField(choices=[('pending', 'قيد الانتظار'), ('passed', 'ناجح'), ('failed', 'راسب')], default='pending', max_length=20, verbose_name='النتيجة')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='التقييم (1-10)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المقابل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobapplication', verbose_name='طلب التوظيف')),
            ],
            options={
                'verbose_name': 'مقابلة',
                'verbose_name_plural': 'المقابلات',
                'db_table': 'Tbl_Interviews',
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(verbose_name='الوصف الوظيفي')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('responsibilities', models.TextField(verbose_name='المسؤوليات')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للراتب')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للراتب')),
                ('vacancies', models.IntegerField(default=1, verbose_name='عدد الشواغر')),
                ('posting_date', models.DateField(verbose_name='تاريخ النشر')),
                ('closing_date', models.DateField(verbose_name='تاريخ الإغلاق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='القسم')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position', verbose_name='المنصب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعلان وظيفي',
                'verbose_name_plural': 'الإعلانات الوظيفية',
                'db_table': 'Tbl_Job_Postings',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting', verbose_name='الإعلان الوظيفي'),
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('task_name', models.CharField(max_length=200, verbose_name='اسم المهمة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة تأهيل',
                'verbose_name_plural': 'مهام التأهيل',
                'db_table': 'Tbl_Onboarding_Tasks',
                'ordering': ['due_date'],
            },
        ),
    ]
