# Generated by Django 5.0 on 2025-11-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('offer_date', models.DateField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='recruitment/offers/', verbose_name='خطاب العرض')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recruitment.jobapplication', verbose_name='طلب التوظيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position', verbose_name='المنصب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'عرض عمل',
                'verbose_name_plural': 'عروض العمل',
                'db_table': 'Tbl_Job_Offers',
                'ordering': ['-offer_date'],
            },
        ),
    ]
