# Generated by Django 5.2.8 on 2025-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAttendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='Attendance_ID', primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_column='Attendance_Date')),
                ('checkin_time', models.DateTimeField(blank=True, db_column='CheckIn_Time', null=True)),
                ('checkout_time', models.DateTimeField(blank=True, db_column='CheckOut_Time', null=True)),
                ('work_hours', models.DecimalField(blank=True, db_column='Work_Hours', decimal_places=2, max_digits=5, null=True)),
                ('late_minutes', models.IntegerField(blank=True, db_column='Late_Minutes', null=True)),
                ('overtime_hours', models.DecimalField(blank=True, db_column='Overtime_Hours', decimal_places=2, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tbl_Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmployees',
            fields=[
                ('emp_id', models.AutoField(db_column='Emp_ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=20, null=True, unique=True)),
                ('emp_fullname', models.CharField(db_column='Emp_FullName', max_length=200)),
                ('national_id', models.CharField(blank=True, db_column='National_ID', max_length=14, null=True)),
                ('job_title', models.CharField(blank=True, db_column='Job_Title', max_length=100, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, db_column='Hire_Date', null=True)),
                ('salary_basic', models.DecimalField(blank=True, db_column='Salary_Basic', decimal_places=2, max_digits=18, null=True)),
                ('salary_housing', models.DecimalField(blank=True, db_column='Salary_Housing', decimal_places=2, max_digits=18, null=True)),
                ('salary_transport', models.DecimalField(blank=True, db_column='Salary_Transport', decimal_places=2, max_digits=18, null=True)),
                ('salary_other', models.DecimalField(blank=True, db_column='Salary_Other', decimal_places=2, max_digits=18, null=True)),
                ('salary_total', models.DecimalField(blank=True, db_column='Salary_Total', decimal_places=2, editable=False, max_digits=21, null=True)),
                ('allowed_annual_leaves', models.IntegerField(blank=True, db_column='Allowed_Annual_Leaves', null=True)),
                ('allowed_sick_leaves', models.IntegerField(blank=True, db_column='Allowed_Sick_Leaves', null=True)),
                ('allowed_casual_leaves', models.IntegerField(blank=True, db_column='Allowed_Casual_Leaves', null=True)),
                ('work_start', models.TimeField(blank=True, db_column='Work_Start', null=True)),
                ('work_end', models.TimeField(blank=True, db_column='Work_End', null=True)),
                ('telegram_userid', models.CharField(blank=True, db_column='Telegram_UserID', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active')),
            ],
            options={
                'db_table': 'Tbl_Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLates',
            fields=[
                ('late_id', models.AutoField(db_column='Late_ID', primary_key=True, serialize=False)),
                ('late_date', models.DateField(db_column='Late_Date')),
                ('late_minutes', models.IntegerField(db_column='Late_Minutes')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=200, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, db_column='Deduction_Amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Tbl_Lates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLeaves',
            fields=[
                ('leave_id', models.AutoField(db_column='Leave_ID', primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_Date', null=True)),
                ('leave_type', models.CharField(blank=True, db_column='Leave_Type', max_length=50, null=True)),
                ('leave_days', models.IntegerField(blank=True, db_column='Leave_Days', editable=False, null=True)),
                ('approved_by', models.CharField(blank=True, db_column='Approved_By', max_length=100, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Tbl_Leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLoans',
            fields=[
                ('loan_id', models.AutoField(db_column='Loan_ID', primary_key=True, serialize=False)),
                ('loan_date', models.DateField(db_column='Loan_Date')),
                ('loan_amount', models.DecimalField(db_column='Loan_Amount', decimal_places=2, max_digits=10)),
                ('repayment_per_month', models.DecimalField(blank=True, db_column='Repayment_Per_Month', decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, db_column='Remaining_Amount', decimal_places=2, max_digits=22, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Tbl_Loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLogs',
            fields=[
                ('log_id', models.AutoField(db_column='Log_ID', primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(blank=True, db_column='Emp_ID', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=100, null=True)),
                ('action_details', models.TextField(blank=True, db_column='Action_Details', null=True)),
                ('performed_by', models.CharField(blank=True, db_column='Performed_By', max_length=100, null=True)),
                ('performed_at', models.DateTimeField(blank=True, db_column='Performed_At', null=True)),
            ],
            options={
                'db_table': 'Tbl_Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOvertime',
            fields=[
                ('ot_id', models.AutoField(db_column='OT_ID', primary_key=True, serialize=False)),
                ('ot_date', models.DateField(db_column='OT_Date')),
                ('ot_hours', models.DecimalField(blank=True, db_column='OT_Hours', decimal_places=2, max_digits=5, null=True)),
                ('ot_type', models.CharField(blank=True, db_column='OT_Type', max_length=20, null=True)),
                ('ot_amount', models.DecimalField(blank=True, db_column='OT_Amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Tbl_Overtime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPayslips',
            fields=[
                ('payslip_id', models.AutoField(db_column='Payslip_ID', primary_key=True, serialize=False)),
                ('period_start', models.DateField(blank=True, db_column='Period_Start', null=True)),
                ('period_end', models.DateField(blank=True, db_column='Period_End', null=True)),
                ('gross_pay', models.DecimalField(blank=True, db_column='Gross_Pay', decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, db_column='Total_Deductions', decimal_places=2, max_digits=10, null=True)),
                ('net_pay', models.DecimalField(blank=True, db_column='Net_Pay', decimal_places=2, max_digits=11, null=True)),
                ('generated_at', models.DateTimeField(blank=True, db_column='Generated_At', null=True)),
                ('payslip_file', models.CharField(blank=True, db_column='Payslip_File', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Tbl_Payslips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSettings',
            fields=[
                ('setting_id', models.AutoField(db_column='Setting_ID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, db_column='Company_Name', max_length=200, null=True)),
                ('workday_start', models.TimeField(db_column='Workday_Start')),
                ('workday_end', models.TimeField(db_column='Workday_End')),
                ('lunch_break_minutes', models.IntegerField(db_column='Lunch_Break_Minutes')),
                ('late_threshold_min', models.IntegerField(db_column='Late_Threshold_Min')),
                ('overtime_rate', models.FloatField(db_column='Overtime_Rate')),
                ('monthly_working_hours', models.FloatField(db_column='Monthly_Working_Hours')),
                ('salary_currency', models.CharField(blank=True, db_column='Salary_Currency', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tbl_Settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStagingAttendance',
            fields=[
                ('staging_id', models.AutoField(db_column='Staging_ID', primary_key=True, serialize=False)),
                ('raw_userid', models.CharField(blank=True, db_column='Raw_UserID', max_length=100, null=True)),
                ('raw_name', models.CharField(blank=True, db_column='Raw_Name', max_length=200, null=True)),
                ('raw_datetime', models.CharField(blank=True, db_column='Raw_DateTime', max_length=100, null=True)),
                ('raw_state', models.CharField(blank=True, db_column='Raw_State', max_length=50, null=True)),
                ('parsed_date', models.DateField(blank=True, db_column='Parsed_Date', null=True)),
                ('parsed_checktime', models.DateTimeField(blank=True, db_column='Parsed_CheckTime', null=True)),
                ('parsed_state', models.CharField(blank=True, db_column='Parsed_State', max_length=50, null=True)),
                ('parsed_emp_id', models.IntegerField(blank=True, db_column='Parsed_Emp_ID', null=True)),
                ('processed', models.BooleanField(blank=True, db_column='Processed', null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_column='Processed_At', null=True)),
                ('errormsg', models.CharField(blank=True, db_column='ErrorMsg', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Tbl_Staging_Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStagingAttendanceLog',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('logtime', models.DateTimeField(db_column='LogTime')),
                ('filename', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('errormessage', models.TextField(blank=True, db_column='ErrorMessage', null=True)),
            ],
            options={
                'db_table': 'Tbl_Staging_Attendance_Log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStagingAttendanceTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_userid', models.CharField(blank=True, db_column='Raw_UserID', max_length=50, null=True)),
                ('raw_name', models.CharField(blank=True, db_column='Raw_Name', max_length=100, null=True)),
                ('raw_datetime', models.CharField(blank=True, db_column='Raw_DateTime', max_length=50, null=True)),
                ('raw_state', models.CharField(blank=True, db_column='Raw_State', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tbl_Staging_Attendance_Temp',
                'managed': False,
            },
        ),
    ]
