# Generated by Django 5.2.8 on 2025-11-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('level', models.IntegerField(verbose_name='المستوى')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='التعليقات')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإجراء')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='attendance.leaverequest', verbose_name='طلب الإجازة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'سير عمل الموافقة',
                'verbose_name_plural': 'سير عمل الموافقات',
                'db_table': 'Tbl_Leave_Approval_Workflow',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السياسة')),
                ('leave_type', models.CharField(max_length=50, verbose_name='نوع الإجازة')),
                ('days_per_year', models.IntegerField(verbose_name='الأيام في السنة')),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأيام المتتالية')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='تتطلب موافقة')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('carry_forward', models.BooleanField(default=False, verbose_name='يمكن ترحيلها')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة إجازة',
                'verbose_name_plural': 'سياسات الإجازات',
                'db_table': 'Tbl_Leave_Policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('leave_type', models.CharField(max_length=50, verbose_name='نوع الإجازة')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('total_days', models.IntegerField(verbose_name='إجمالي الأيام')),
                ('used_days', models.IntegerField(default=0, verbose_name='الأيام المستخدمة')),
                ('remaining_days', models.IntegerField(verbose_name='الأيام المتبقية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'db_table': 'Tbl_Leave_Balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
