# Generated by Django 5.2.8 on 2025-11-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('bonus_type', models.CharField(choices=[('performance', 'أداء'), ('annual', 'سنوية'), ('project', 'مشروع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المكافأة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'db_table': 'Tbl_Bonuses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القرض')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط')),
                ('number_of_installments', models.IntegerField(verbose_name='عدد الأقساط')),
                ('paid_installments', models.IntegerField(default=0, verbose_name='الأقساط المدفوعة')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
                'db_table': 'Tbl_Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل النقل')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدلات أخرى')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ العمل الإضافي')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافأة')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الغياب')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأخير')),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم القرض')),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأمين')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الضريبة')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصومات أخرى')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الراتب')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الخصومات')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('processing', 'قيد المعالجة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة الدفع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'راتب',
                'verbose_name_plural': 'الرواتب',
                'db_table': 'Tbl_Payrolls',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('payslip_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القسيمة')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/', verbose_name='ملف PDF')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payroll', verbose_name='الراتب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'db_table': 'Tbl_Payslips',
                'ordering': ['-generated_date'],
            },
        ),
    ]
