# Generated by Django 5.2.8 on 2025-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('on_leave', 'في إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ساعات العمل')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='دقائق المغادرة المبكرة')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل الإضافي')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'db_table': 'Tbl_Attendance_New',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='الوقت')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='معرف الجهاز')),
                ('punch_type', models.CharField(choices=[('check_in', 'حضور'), ('check_out', 'انصراف'), ('break_out', 'بداية استراحة'), ('break_in', 'نهاية استراحة')], default='check_in', max_length=20, verbose_name='نوع التسجيل')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمة',
                'db_table': 'Tbl_Attendance_Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('unpaid', 'إجازة بدون راتب'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة'), ('hajj', 'إجازة حج'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.IntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/attachments/', verbose_name='مرفق')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'db_table': 'Tbl_Leave_Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الساعات')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'عمل إضافي',
                'verbose_name_plural': 'العمل الإضافي',
                'db_table': 'Tbl_Overtime',
                'ordering': ['-date'],
            },
        ),
    ]
