# Generated by Django 5.2.8 on 2025-11-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'فئة مهارة',
                'verbose_name_plural': 'فئات المهارات',
                'db_table': 'Tbl_Skill_Categories',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهارة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.skillcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
                'db_table': 'Tbl_Skills',
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('status', models.CharField(choices=[('registered', 'مسجل'), ('attended', 'حضر'), ('completed', 'أكمل'), ('failed', 'راسب'), ('cancelled', 'ملغى')], default='registered', max_length=20, verbose_name='الحالة')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الحضور')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='تم إصدار الشهادة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'تسجيل تدريبي',
                'verbose_name_plural': 'التسجيلات التدريبية',
                'db_table': 'Tbl_Training_Enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='training/certificates/', verbose_name='ملف الشهادة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='training.trainingenrollment', verbose_name='التسجيل التدريبي')),
            ],
            options={
                'verbose_name': 'شهادة تدريب',
                'verbose_name_plural': 'شهادات التدريب',
                'db_table': 'Tbl_Training_Certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('objectives', models.TextField(verbose_name='الأهداف')),
                ('duration_hours', models.IntegerField(verbose_name='المدة (ساعات)')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('trainer', models.CharField(max_length=200, verbose_name='المدرب')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('max_participants', models.IntegerField(verbose_name='الحد الأقصى للمشاركين')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('ongoing', 'جاري'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='planned', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'برنامج تدريبي',
                'verbose_name_plural': 'البرامج التدريبية',
                'db_table': 'Tbl_Training_Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='training_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingprogram', verbose_name='البرنامج التدريبي'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], max_length=20, verbose_name='مستوى الكفاءة')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='سنوات الخبرة')),
                ('last_used_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر استخدام')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.skill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'مهارة موظف',
                'verbose_name_plural': 'مهارات الموظفين',
                'db_table': 'Tbl_Employee_Skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together={('employee', 'training_program')},
        ),
    ]
